-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
-- VALUES(100001, 'ASD', 'MY DINH', CURDATE());
-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
-- VALUES(100002, 'ASD', 'MY DINH', CURRENT_DATE());
--
-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
-- VALUES(100003, 'ASD', 'MY DINH', SYSDATE()); -- only MySQL, not for H2
--
-- INSERT INTO PERSON (ID, NAME, LOCATION, BIRTH_DATE)
-- VALUES(100004, 'ASD', 'MY DINH', CURRENT_TIMESTAMP());

-- auto generate id
INSERT INTO PERSON (NAME, LOCATION, BIRTH_DATE)
VALUES('ASD', 'MY DINH', CURDATE());
INSERT INTO PERSON (NAME, LOCATION, BIRTH_DATE)
VALUES('ASD', 'MY DINH', CURRENT_DATE());

INSERT INTO PERSON (NAME, LOCATION, BIRTH_DATE)
VALUES('ASD', 'MY DINH', SYSDATE()); -- only MySQL, not for H2

INSERT INTO PERSON (NAME, LOCATION, BIRTH_DATE)
VALUES('ASD', 'MY DINH', CURRENT_TIMESTAMP());


